# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 200
        min-spare-threads: 75
    port: 80
    connection-timeout: 15000
    servlet:
      context-path: /delay
     
# mysql
spring: 
    # 环境 dev|test|pro
    profiles:
        active: test
    # jackson时间格式化
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    servlet:
      multipart:
        enabled: true
        max-request-size: 100MB
        max-file-size: 100MB
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
    aop: 
        auto: true 
        proxy-target-class: true 
delay-service-config:
  handlerConfig:
    - handlerName: JdkDelayMessageListener
      handlerClassName: org.jackdking.delay.domainv1.delayService.handlers.JdkDelayMessageHandler
  listenerConfig:
    - listenerName: JdkDelayMessageListener
      listenerClassName: org.jackdking.delay.domainv1.delayService.listener.JdkDelayMessageListener
      handlerName:
        - JdkDelayMessageListener
#延迟服务 客户端-服务端通信  server侧的端口号,默认9999
delay-netty-server:
  port: 9999